package com.sspuiur.model;

// Generated Mar 27, 2016 10:45:43 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * SspuIurPositionSalary generated by hbm2java
 */
public class SspuIurPositionSalary implements java.io.Serializable {

	private Integer id;
	private SspuIurPayCheck sspuIurPayCheck;
	private int PId;
	private Double actualSalary;
	private Double totalSalary;
	private Double basicSalary;
	private Double feeDeduction;
	private Double taxableAmount;
	private Double pushMoney;
	private Double welfarePayments;
	private Byte payStatus;
	private Set sspuIurAssociationSalaries = new HashSet(0);

	public SspuIurPositionSalary() {
	}

	public SspuIurPositionSalary(SspuIurPayCheck sspuIurPayCheck, int PId) {
		this.sspuIurPayCheck = sspuIurPayCheck;
		this.PId = PId;
	}

	public SspuIurPositionSalary(SspuIurPayCheck sspuIurPayCheck, int PId,
			Double actualSalary, Double totalSalary, Double basicSalary,
			Double feeDeduction, Double taxableAmount, Double pushMoney,
			Double welfarePayments, Byte payStatus,
			Set sspuIurAssociationSalaries) {
		this.sspuIurPayCheck = sspuIurPayCheck;
		this.PId = PId;
		this.actualSalary = actualSalary;
		this.totalSalary = totalSalary;
		this.basicSalary = basicSalary;
		this.feeDeduction = feeDeduction;
		this.taxableAmount = taxableAmount;
		this.pushMoney = pushMoney;
		this.welfarePayments = welfarePayments;
		this.payStatus = payStatus;
		this.sspuIurAssociationSalaries = sspuIurAssociationSalaries;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public SspuIurPayCheck getSspuIurPayCheck() {
		return this.sspuIurPayCheck;
	}

	public void setSspuIurPayCheck(SspuIurPayCheck sspuIurPayCheck) {
		this.sspuIurPayCheck = sspuIurPayCheck;
	}

	public int getPId() {
		return this.PId;
	}

	public void setPId(int PId) {
		this.PId = PId;
	}

	public Double getActualSalary() {
		return this.actualSalary;
	}

	public void setActualSalary(Double actualSalary) {
		this.actualSalary = actualSalary;
	}

	public Double getTotalSalary() {
		return this.totalSalary;
	}

	public void setTotalSalary(Double totalSalary) {
		this.totalSalary = totalSalary;
	}

	public Double getBasicSalary() {
		return this.basicSalary;
	}

	public void setBasicSalary(Double basicSalary) {
		this.basicSalary = basicSalary;
	}

	public Double getFeeDeduction() {
		return this.feeDeduction;
	}

	public void setFeeDeduction(Double feeDeduction) {
		this.feeDeduction = feeDeduction;
	}

	public Double getTaxableAmount() {
		return this.taxableAmount;
	}

	public void setTaxableAmount(Double taxableAmount) {
		this.taxableAmount = taxableAmount;
	}

	public Double getPushMoney() {
		return this.pushMoney;
	}

	public void setPushMoney(Double pushMoney) {
		this.pushMoney = pushMoney;
	}

	public Double getWelfarePayments() {
		return this.welfarePayments;
	}

	public void setWelfarePayments(Double welfarePayments) {
		this.welfarePayments = welfarePayments;
	}

	public Byte getPayStatus() {
		return this.payStatus;
	}

	public void setPayStatus(Byte payStatus) {
		this.payStatus = payStatus;
	}

	public Set getSspuIurAssociationSalaries() {
		return this.sspuIurAssociationSalaries;
	}

	public void setSspuIurAssociationSalaries(Set sspuIurAssociationSalaries) {
		this.sspuIurAssociationSalaries = sspuIurAssociationSalaries;
	}

}
