package com.sspuiur.model;

// Generated Mar 27, 2016 10:45:43 AM by Hibernate Tools 4.0.0

/**
 * SspuIurRole generated by hbm2java
 */
public class SspuIurRole implements java.io.Serializable {

	private Integer id;
	private Byte identity;
	private Integer identityId;
	private int menuId;
	private Byte roleLevel;
	private Byte status;

	public SspuIurRole() {
	}

	public SspuIurRole(int menuId) {
		this.menuId = menuId;
	}

	public SspuIurRole(Byte identity, Integer identityId, int menuId,
			Byte roleLevel, Byte status) {
		this.identity = identity;
		this.identityId = identityId;
		this.menuId = menuId;
		this.roleLevel = roleLevel;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Byte getIdentity() {
		return this.identity;
	}

	public void setIdentity(Byte identity) {
		this.identity = identity;
	}

	public Integer getIdentityId() {
		return this.identityId;
	}

	public void setIdentityId(Integer identityId) {
		this.identityId = identityId;
	}

	public int getMenuId() {
		return this.menuId;
	}

	public void setMenuId(int menuId) {
		this.menuId = menuId;
	}

	public Byte getRoleLevel() {
		return this.roleLevel;
	}

	public void setRoleLevel(Byte roleLevel) {
		this.roleLevel = roleLevel;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
