package com.sspuiur.model;

// Generated Mar 27, 2016 10:45:43 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * SspuIurStudent generated by hbm2java
 */
public class SspuIurStudent implements java.io.Serializable {

	private Integer id;
	private Integer UId;
	private String studentId;
	private String name;
	private Byte sex;
	private String phoneNumber1;
	private String phoneNumber2;
	private String qq;
	private String mail;
	private String address;
	private Date entranceTime;
	private Date graduationTime;
	private Date birthday;
	private Byte status;

	public SspuIurStudent() {
	}

	public SspuIurStudent(Integer UId, String studentId, String name, Byte sex,
			String phoneNumber1, String phoneNumber2, String qq, String mail,
			String address, Date entranceTime, Date graduationTime,
			Date birthday, Byte status) {
		this.UId = UId;
		this.studentId = studentId;
		this.name = name;
		this.sex = sex;
		this.phoneNumber1 = phoneNumber1;
		this.phoneNumber2 = phoneNumber2;
		this.qq = qq;
		this.mail = mail;
		this.address = address;
		this.entranceTime = entranceTime;
		this.graduationTime = graduationTime;
		this.birthday = birthday;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

	public String getStudentId() {
		return this.studentId;
	}

	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Byte getSex() {
		return this.sex;
	}

	public void setSex(Byte sex) {
		this.sex = sex;
	}

	public String getPhoneNumber1() {
		return this.phoneNumber1;
	}

	public void setPhoneNumber1(String phoneNumber1) {
		this.phoneNumber1 = phoneNumber1;
	}

	public String getPhoneNumber2() {
		return this.phoneNumber2;
	}

	public void setPhoneNumber2(String phoneNumber2) {
		this.phoneNumber2 = phoneNumber2;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getEntranceTime() {
		return this.entranceTime;
	}

	public void setEntranceTime(Date entranceTime) {
		this.entranceTime = entranceTime;
	}

	public Date getGraduationTime() {
		return this.graduationTime;
	}

	public void setGraduationTime(Date graduationTime) {
		this.graduationTime = graduationTime;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
