package com.sspuiur.model;

// Generated Mar 27, 2016 10:45:43 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * SspuIurPositionReview generated by hbm2java
 */
public class SspuIurPositionReview implements java.io.Serializable {

	private Integer id;
	private Integer prId;
	private String reviewContent;
	private String reviewer;
	private Date reviewTime;
	private Byte status;

	public SspuIurPositionReview() {
	}

	public SspuIurPositionReview(Integer prId, String reviewContent,
			String reviewer, Date reviewTime, Byte status) {
		this.prId = prId;
		this.reviewContent = reviewContent;
		this.reviewer = reviewer;
		this.reviewTime = reviewTime;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPrId() {
		return this.prId;
	}

	public void setPrId(Integer prId) {
		this.prId = prId;
	}

	public String getReviewContent() {
		return this.reviewContent;
	}

	public void setReviewContent(String reviewContent) {
		this.reviewContent = reviewContent;
	}

	public String getReviewer() {
		return this.reviewer;
	}

	public void setReviewer(String reviewer) {
		this.reviewer = reviewer;
	}

	public Date getReviewTime() {
		return this.reviewTime;
	}

	public void setReviewTime(Date reviewTime) {
		this.reviewTime = reviewTime;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
