package com.sspuiur.model;

// Generated Mar 27, 2016 10:45:43 AM by Hibernate Tools 4.0.0

/**
 * SspuIurDbTable generated by hbm2java
 */
public class SspuIurDbTable implements java.io.Serializable {

	private Integer id;
	private SspuIurDbCode sspuIurDbCode;
	private String tableName;
	private String tableDescription;
	private Byte status;

	public SspuIurDbTable() {
	}

	public SspuIurDbTable(SspuIurDbCode sspuIurDbCode) {
		this.sspuIurDbCode = sspuIurDbCode;
	}

	public SspuIurDbTable(SspuIurDbCode sspuIurDbCode, String tableName,
			String tableDescription, Byte status) {
		this.sspuIurDbCode = sspuIurDbCode;
		this.tableName = tableName;
		this.tableDescription = tableDescription;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public SspuIurDbCode getSspuIurDbCode() {
		return this.sspuIurDbCode;
	}

	public void setSspuIurDbCode(SspuIurDbCode sspuIurDbCode) {
		this.sspuIurDbCode = sspuIurDbCode;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getTableDescription() {
		return this.tableDescription;
	}

	public void setTableDescription(String tableDescription) {
		this.tableDescription = tableDescription;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
