package com.sspuiur.model;

// Generated Mar 27, 2016 10:45:43 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SspuIurPosition generated by hbm2java
 */
public class SspuIurPosition implements java.io.Serializable {

	private Integer id;
	private int CId;
	private String name;
	private String amount;
	private String workHours;
	private String salary;
	private Date applyStart;
	private Date applyEnd;
	private Byte universityGrades;
	private Byte category;
	private String type;
	private Byte degreeRequirement;
	private String PTask;
	private String PRequirement;
	private String POtherNotes;
	private Byte status;
	private Set sspuIurPositionRecords = new HashSet(0);

	public SspuIurPosition() {
	}

	public SspuIurPosition(int CId) {
		this.CId = CId;
	}

	public SspuIurPosition(int CId, String name, String amount,
			String workHours, String salary, Date applyStart, Date applyEnd,
			Byte universityGrades, Byte category, String type,
			Byte degreeRequirement, String PTask, String PRequirement,
			String POtherNotes, Byte status, Set sspuIurPositionRecords) {
		this.CId = CId;
		this.name = name;
		this.amount = amount;
		this.workHours = workHours;
		this.salary = salary;
		this.applyStart = applyStart;
		this.applyEnd = applyEnd;
		this.universityGrades = universityGrades;
		this.category = category;
		this.type = type;
		this.degreeRequirement = degreeRequirement;
		this.PTask = PTask;
		this.PRequirement = PRequirement;
		this.POtherNotes = POtherNotes;
		this.status = status;
		this.sspuIurPositionRecords = sspuIurPositionRecords;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getCId() {
		return this.CId;
	}

	public void setCId(int CId) {
		this.CId = CId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	public String getWorkHours() {
		return this.workHours;
	}

	public void setWorkHours(String workHours) {
		this.workHours = workHours;
	}

	public String getSalary() {
		return this.salary;
	}

	public void setSalary(String salary) {
		this.salary = salary;
	}

	public Date getApplyStart() {
		return this.applyStart;
	}

	public void setApplyStart(Date applyStart) {
		this.applyStart = applyStart;
	}

	public Date getApplyEnd() {
		return this.applyEnd;
	}

	public void setApplyEnd(Date applyEnd) {
		this.applyEnd = applyEnd;
	}

	public Byte getUniversityGrades() {
		return this.universityGrades;
	}

	public void setUniversityGrades(Byte universityGrades) {
		this.universityGrades = universityGrades;
	}

	public Byte getCategory() {
		return this.category;
	}

	public void setCategory(Byte category) {
		this.category = category;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Byte getDegreeRequirement() {
		return this.degreeRequirement;
	}

	public void setDegreeRequirement(Byte degreeRequirement) {
		this.degreeRequirement = degreeRequirement;
	}

	public String getPTask() {
		return this.PTask;
	}

	public void setPTask(String PTask) {
		this.PTask = PTask;
	}

	public String getPRequirement() {
		return this.PRequirement;
	}

	public void setPRequirement(String PRequirement) {
		this.PRequirement = PRequirement;
	}

	public String getPOtherNotes() {
		return this.POtherNotes;
	}

	public void setPOtherNotes(String POtherNotes) {
		this.POtherNotes = POtherNotes;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Set getSspuIurPositionRecords() {
		return this.sspuIurPositionRecords;
	}

	public void setSspuIurPositionRecords(Set sspuIurPositionRecords) {
		this.sspuIurPositionRecords = sspuIurPositionRecords;
	}

}
