package com.sspuiur.model;

// Generated Mar 27, 2016 10:45:43 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * SspuIurPositionRecord generated by hbm2java
 */
public class SspuIurPositionRecord implements java.io.Serializable {

	private Integer id;
	private SspuIurPosition sspuIurPosition;
	private String title;
	private String content;
	private String creator;
	private Date createTime;
	private String editor;
	private Date editTime;
	private String reviewer;
	private Byte reviewState;
	private Byte status;

	public SspuIurPositionRecord() {
	}

	public SspuIurPositionRecord(SspuIurPosition sspuIurPosition) {
		this.sspuIurPosition = sspuIurPosition;
	}

	public SspuIurPositionRecord(SspuIurPosition sspuIurPosition, String title,
			String content, String creator, Date createTime, String editor,
			Date editTime, String reviewer, Byte reviewState, Byte status) {
		this.sspuIurPosition = sspuIurPosition;
		this.title = title;
		this.content = content;
		this.creator = creator;
		this.createTime = createTime;
		this.editor = editor;
		this.editTime = editTime;
		this.reviewer = reviewer;
		this.reviewState = reviewState;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public SspuIurPosition getSspuIurPosition() {
		return this.sspuIurPosition;
	}

	public void setSspuIurPosition(SspuIurPosition sspuIurPosition) {
		this.sspuIurPosition = sspuIurPosition;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getEditor() {
		return this.editor;
	}

	public void setEditor(String editor) {
		this.editor = editor;
	}

	public Date getEditTime() {
		return this.editTime;
	}

	public void setEditTime(Date editTime) {
		this.editTime = editTime;
	}

	public String getReviewer() {
		return this.reviewer;
	}

	public void setReviewer(String reviewer) {
		this.reviewer = reviewer;
	}

	public Byte getReviewState() {
		return this.reviewState;
	}

	public void setReviewState(Byte reviewState) {
		this.reviewState = reviewState;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
