package com.sspuiur.model;

// Generated Mar 27, 2016 10:45:43 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * SspuIurUser generated by hbm2java
 */
public class SspuIurUser implements java.io.Serializable {

	private Integer id;
	private int roleId;
	private String username;
	private String password;
	private Date createTime;
	private String creator;
	private Date editTime;
	private String editor;
	private Date loginTime;
	private Byte status;

	public SspuIurUser() {
	}

	public SspuIurUser(int roleId) {
		this.roleId = roleId;
	}

	public SspuIurUser(int roleId, String username, String password,
			Date createTime, String creator, Date editTime, String editor,
			Date loginTime, Byte status) {
		this.roleId = roleId;
		this.username = username;
		this.password = password;
		this.createTime = createTime;
		this.creator = creator;
		this.editTime = editTime;
		this.editor = editor;
		this.loginTime = loginTime;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getEditTime() {
		return this.editTime;
	}

	public void setEditTime(Date editTime) {
		this.editTime = editTime;
	}

	public String getEditor() {
		return this.editor;
	}

	public void setEditor(String editor) {
		this.editor = editor;
	}

	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
