package com.sspuiur.model;

// Generated Mar 27, 2016 10:45:43 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * SspuIurCompany generated by hbm2java
 */
public class SspuIurCompany implements java.io.Serializable {

	private Integer id;
	private String name;
	private String englishName;
	private String telephone;
	private String mail;
	private String website;
	private String address;
	private String type;
	private String category;
	private Integer staffNumber;
	private Date createTime;
	private String notes;
	private Byte status;

	public SspuIurCompany() {
	}

	public SspuIurCompany(String name, String englishName, String telephone,
			String mail, String website, String address, String type,
			String category, Integer staffNumber, Date createTime,
			String notes, Byte status) {
		this.name = name;
		this.englishName = englishName;
		this.telephone = telephone;
		this.mail = mail;
		this.website = website;
		this.address = address;
		this.type = type;
		this.category = category;
		this.staffNumber = staffNumber;
		this.createTime = createTime;
		this.notes = notes;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEnglishName() {
		return this.englishName;
	}

	public void setEnglishName(String englishName) {
		this.englishName = englishName;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public Integer getStaffNumber() {
		return this.staffNumber;
	}

	public void setStaffNumber(Integer staffNumber) {
		this.staffNumber = staffNumber;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
