package com.sspuiur.model;

// Generated Mar 27, 2016 10:45:43 AM by Hibernate Tools 4.0.0

/**
 * SspuIurStudentSparetime generated by hbm2java
 */
public class SspuIurStudentSparetime implements java.io.Serializable {

	private Integer id;
	private int SId;
	private Byte monday;
	private Byte tuesday;
	private Byte wednesday;
	private Byte thursday;
	private Byte friday;

	public SspuIurStudentSparetime() {
	}

	public SspuIurStudentSparetime(int SId) {
		this.SId = SId;
	}

	public SspuIurStudentSparetime(int SId, Byte monday, Byte tuesday,
			Byte wednesday, Byte thursday, Byte friday) {
		this.SId = SId;
		this.monday = monday;
		this.tuesday = tuesday;
		this.wednesday = wednesday;
		this.thursday = thursday;
		this.friday = friday;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getSId() {
		return this.SId;
	}

	public void setSId(int SId) {
		this.SId = SId;
	}

	public Byte getMonday() {
		return this.monday;
	}

	public void setMonday(Byte monday) {
		this.monday = monday;
	}

	public Byte getTuesday() {
		return this.tuesday;
	}

	public void setTuesday(Byte tuesday) {
		this.tuesday = tuesday;
	}

	public Byte getWednesday() {
		return this.wednesday;
	}

	public void setWednesday(Byte wednesday) {
		this.wednesday = wednesday;
	}

	public Byte getThursday() {
		return this.thursday;
	}

	public void setThursday(Byte thursday) {
		this.thursday = thursday;
	}

	public Byte getFriday() {
		return this.friday;
	}

	public void setFriday(Byte friday) {
		this.friday = friday;
	}

}
