package com.sspuiur.model;

// Generated Mar 27, 2016 10:45:43 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SspuIurResearch generated by hbm2java
 */
public class SspuIurResearch implements java.io.Serializable {

	private Integer id;
	private String projectName;
	private Double researchFunds;
	private Date startTime;
	private Date endTiem;
	private String projectSummary;
	private String projectObjective;
	private Date applyTime;
	private String applicantName;
	private String category;
	private Byte status;
	private Set sspuIurResearchTeams = new HashSet(0);

	public SspuIurResearch() {
	}

	public SspuIurResearch(String projectName, Double researchFunds,
			Date startTime, Date endTiem, String projectSummary,
			String projectObjective, Date applyTime, String applicantName,
			String category, Byte status, Set sspuIurResearchTeams) {
		this.projectName = projectName;
		this.researchFunds = researchFunds;
		this.startTime = startTime;
		this.endTiem = endTiem;
		this.projectSummary = projectSummary;
		this.projectObjective = projectObjective;
		this.applyTime = applyTime;
		this.applicantName = applicantName;
		this.category = category;
		this.status = status;
		this.sspuIurResearchTeams = sspuIurResearchTeams;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public Double getResearchFunds() {
		return this.researchFunds;
	}

	public void setResearchFunds(Double researchFunds) {
		this.researchFunds = researchFunds;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTiem() {
		return this.endTiem;
	}

	public void setEndTiem(Date endTiem) {
		this.endTiem = endTiem;
	}

	public String getProjectSummary() {
		return this.projectSummary;
	}

	public void setProjectSummary(String projectSummary) {
		this.projectSummary = projectSummary;
	}

	public String getProjectObjective() {
		return this.projectObjective;
	}

	public void setProjectObjective(String projectObjective) {
		this.projectObjective = projectObjective;
	}

	public Date getApplyTime() {
		return this.applyTime;
	}

	public void setApplyTime(Date applyTime) {
		this.applyTime = applyTime;
	}

	public String getApplicantName() {
		return this.applicantName;
	}

	public void setApplicantName(String applicantName) {
		this.applicantName = applicantName;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Set getSspuIurResearchTeams() {
		return this.sspuIurResearchTeams;
	}

	public void setSspuIurResearchTeams(Set sspuIurResearchTeams) {
		this.sspuIurResearchTeams = sspuIurResearchTeams;
	}

}
