package com.sspuiur.model;

// Generated Mar 27, 2016 10:45:43 AM by Hibernate Tools 4.0.0

/**
 * SspuIurResearchTeam generated by hbm2java
 */
public class SspuIurResearchTeam implements java.io.Serializable {

	private Integer id;
	private SspuIurResearch sspuIurResearch;
	private Integer participantId;
	private Byte isLeader;
	private Byte identity;

	public SspuIurResearchTeam() {
	}

	public SspuIurResearchTeam(SspuIurResearch sspuIurResearch) {
		this.sspuIurResearch = sspuIurResearch;
	}

	public SspuIurResearchTeam(SspuIurResearch sspuIurResearch,
			Integer participantId, Byte isLeader, Byte identity) {
		this.sspuIurResearch = sspuIurResearch;
		this.participantId = participantId;
		this.isLeader = isLeader;
		this.identity = identity;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public SspuIurResearch getSspuIurResearch() {
		return this.sspuIurResearch;
	}

	public void setSspuIurResearch(SspuIurResearch sspuIurResearch) {
		this.sspuIurResearch = sspuIurResearch;
	}

	public Integer getParticipantId() {
		return this.participantId;
	}

	public void setParticipantId(Integer participantId) {
		this.participantId = participantId;
	}

	public Byte getIsLeader() {
		return this.isLeader;
	}

	public void setIsLeader(Byte isLeader) {
		this.isLeader = isLeader;
	}

	public Byte getIdentity() {
		return this.identity;
	}

	public void setIdentity(Byte identity) {
		this.identity = identity;
	}

}
