package com.sspuiur.model;

// Generated Mar 27, 2016 10:45:43 AM by Hibernate Tools 4.0.0

/**
 * SspuIurStudentFamily generated by hbm2java
 */
public class SspuIurStudentFamily implements java.io.Serializable {

	private Integer id;
	private int SId;
	private String name;
	private Byte sex;
	private String relationship;
	private String workplace;
	private String occupation;

	public SspuIurStudentFamily() {
	}

	public SspuIurStudentFamily(int SId) {
		this.SId = SId;
	}

	public SspuIurStudentFamily(int SId, String name, Byte sex,
			String relationship, String workplace, String occupation) {
		this.SId = SId;
		this.name = name;
		this.sex = sex;
		this.relationship = relationship;
		this.workplace = workplace;
		this.occupation = occupation;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getSId() {
		return this.SId;
	}

	public void setSId(int SId) {
		this.SId = SId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Byte getSex() {
		return this.sex;
	}

	public void setSex(Byte sex) {
		this.sex = sex;
	}

	public String getRelationship() {
		return this.relationship;
	}

	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}

	public String getWorkplace() {
		return this.workplace;
	}

	public void setWorkplace(String workplace) {
		this.workplace = workplace;
	}

	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

}
