package com.sspuiur.model;

// Generated Mar 27, 2016 10:45:43 AM by Hibernate Tools 4.0.0

/**
 * SspuIurMenu generated by hbm2java
 */
public class SspuIurMenu implements java.io.Serializable {

	private Integer id;
	private SspuIurMenuPath sspuIurMenuPath;
	private int roleId;

	public SspuIurMenu() {
	}

	public SspuIurMenu(SspuIurMenuPath sspuIurMenuPath, int roleId) {
		this.sspuIurMenuPath = sspuIurMenuPath;
		this.roleId = roleId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public SspuIurMenuPath getSspuIurMenuPath() {
		return this.sspuIurMenuPath;
	}

	public void setSspuIurMenuPath(SspuIurMenuPath sspuIurMenuPath) {
		this.sspuIurMenuPath = sspuIurMenuPath;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

}
